title: Haley Raizes Portfolio
email: hraizes99@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/hraizes.github.io"
url: "https://www.haleysmiles.com"

# Author settings
author: Haley Raizes
author-pic: haley-face.jpg
about-author: I am a fourth-year undergraduate pursuing a B.S. in Computer Science at the University of California, Davis. Take a look around my website to learn about the things that make me smile, which includes running many miles.

# Contact links
email: hrraizes@ucdavis.edu
linkedin: hraizes
github: hraizes
writing: https://www.hercampus.com/author/haley-raizes

# Newsletter
# mailchimp: # Add your MailChimp form identifier.

# Disqus
# discus_identifier: mr-brown # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
