title: Haley Raizes Portfolio
email: hraizes99@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/hraizes.github.io" # the subpath of your site, e.g. /blog
url: "https://www.haleysmiles.com" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Haley Raizes # add your name
author-pic: haley-face.jpg
about-author: The name of my website has two interpretations, Haley Smiles and Haley's Miles. I have collected many hats over the years and this website is intended to give a glimpse into each. In laymans terms, I am a fourth year undergraduate pursuing a B.S. in Computer Science and a minor in Philosophy at the University of California, Davis. I worked as a research assistant in the Cognition in Context Lab at the Center for Mind and Brain during my junior year. My main topics of interest include the development of creative problem solving, resilience, and delayed gratification during childhood.|When I am not at the library, you can find me running around the city of Davis, preparing for my second marathon. For the past two years, I coached Cross Country and Track at Harper Middle school in Davis. Outside of running, I love the outdoors - my two newest endeavors include rock climbing and mountain biking. | When I need a break from using my left brain, I enjoy writing, practicing my French, or re-reading my favorite books, We Are All Completely Beside Ourselves and Steppenwolf. I am also the Director of Speakers Outreach for TEDxUCDavis 2020. We are holding an online conference under the theme of What's Ne(x)t? in the Spring of 2020.

# Contact links
email: # Add your Email address
linkedin: # Add your Linkedin handle
github: hraizes # Add your Github handle
writing: https://www.hercampus.com/author/haley-raizes

# Newsletter
# mailchimp: # Add your MailChimp form identifier.

# Disqus
# discus_identifier: mr-brown # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
