title: Haley Raizes Portfolio
email: hraizes99@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/hraizes.github.io" # the subpath of your site, e.g. /blog
url: "https://www.haleysmiles.com" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Haley Raizes # add your name
author-pic: haley-face.jpg
about-author: My name is Haley Raizes.

# Contact links
email: # Add your Email address
linkedin: # Add your Linkedin handle
github: artemsheludko # Add your Github handle

# Newsletter
# mailchimp: # Add your MailChimp form identifier.

# Disqus
# discus_identifier: mr-brown # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
